spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db.lpkvkwrfbjlpbrvvrhzl.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: ${SUPABASE_DB_PASSWORD:jWez3RnM8B!t8-%}

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG