spring:
  application:
    name: YiSuSystem
  datasource:
    # 替换为 Supabase 连接信息
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db.lpkvkwrfbjlpbrvvrhzl.supabase.co:5432/postgres
    username: postgres
    password: "jWez3RnM8B!t8-%"
#  datasource:
#    url: jdbc:mysql://localhost:3306/yisuhotel?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yisusystem.pojo.entity
  type-handlers-package: com.yisusystem.handler
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

server:
  port: 8080